# Generated by Django 5.1.3 on 2024-11-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_place_date_visited_place_notes_place_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
