# Generated by Django 5.1.3 on 2024-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0003_alter_place_date_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
